# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d323362b04195776d821f602a03d3d8e"
application_url = "https://midwest-heights-output-regarding.trycloudflare.com"
embedded = true
name = "guest-pos"
handle = "guest-pos"

[build]
include_config_on_deploy = true
dev_store_url = "maxfoodstore.myshopify.com"
automatically_update_urls_on_dev = true

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_files,read_fulfillments,read_inventory,read_locations,read_metaobjects,read_orders,read_themes,write_customers,write_files,write_fulfillments,write_inventory,write_locations,write_metaobjects,write_orders,write_products,write_themes"

[auth]
redirect_urls = [
  "https://midwest-heights-output-regarding.trycloudflare.com/auth/callback",
  "https://midwest-heights-output-regarding.trycloudflare.com/auth/shopify/callback",
  "https://midwest-heights-output-regarding.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
